# Generated by Django 4.1.7 on 2023-03-17 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.SmallIntegerField(choices=[(0, 'To do'), (1, 'Done')], default=0, verbose_name='прогресс')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='издатель')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
                'ordering': ('progress',),
            },
        ),
    ]
