# Generated by Django 4.1.7 on 2023-03-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='login'),
        ),
    ]
